### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [mreylmzz/LandFill_Site_Selection_Plugin#1]
Please remove https://github.com/mreylmzz/LandFill_Site_Selection_Plugin/tree/main/landfill_site_selection/__pycache__, it's auto-generated on install

**Comment by mreylmzz** [comment]
> Please remove https://github.com/mreylmzz/LandFill_Site_Selection_Plugin/tree/main/landfill_site_selection/__pycache__, it's auto-generated on install

I have done. Thanks.
